# This is a basic workflow to help you get started with Actions

name: Build and Publish NeoAgi.Policy.DiscoveryAgent Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push of a new tag
  push:
    tags: [ 'v*' ] 
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build_image:
    runs-on: ubuntu-latest

    env:
      KEY_ID: ${{ secrets.NEOAGI_CODE_ARTIFACT_CI_KEY_ID }}
      ACCESS_KEY: ${{ secrets.NEOAGI_CODE_ARTIFACT_CI_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Notify
        uses: neoagi/actions-slack-notify@v1
        with:
            action-message: "${{ github.ref_name }} with SHA of ${{ github.sha }} Starting Build"

      - name: Init Workflow Variables
        run: echo "TAG_NAME=$(echo ${{ github.ref_name }} | sed s/v//)" >> $GITHUB_ENV

      - name: Test Var
        run: echo "Tag Name - ${{ env.TAG_NAME }}"